### ISSUE TITLE
npm no longer in the image

### ISSUE THREAD

**Issue by weimeilin79** [redpanda-data-university/rp-102-stream-processing#4]
Community reported running into error when doing **Stream Processing Lab**
 https://university.redpanda.com/courses/take/hands-on-redpanda-stream-processing/texts/37830438-redpanda-data-transforms-tutorial

When generating the folder, prompt saying NPM not found. 
I think the redpanda image no long includes it.

**Comment by weimeilin79** [comment]
Also getting an error when running build locally... 
I will also ask internally
```
stack: "ModuleNotFoundError: Module not found: Error: Can't resolve '@redpanda-data/wasm-api' in '/Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/src'\n" +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/Compilation.js:2016:28\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:805:13\n' +
      '    at eval (eval at create (/Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:272:22\n' +
      '    at eval (eval at create (/Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:436:22\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:118:11\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:677:25\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:881:8\n' +
      '    at /Users/christina/Desktop/workrepo/rp-102-stream-processing/01-stream-processing-basics/transforms/mask-card/node_modules/webpack/lib/NormalModuleFactory.js:1001:5
```

**Comment by weimeilin79** [comment]
fixed above problem ^^^ should works now. 
Not sure why, but masking doesn't really works.
Maybe it's just me, can you try it? 
```
rpk cluster config set enable_coproc true --brokers localhost:9092

rpk wasm generate mask-card
cd transforms/mask-card

(vectorizedio/wasm-api  to redpanda-data/wasm-api  in main.js) <-- fixed by Eng

rpk topic create purchases --partitions 4 --replicas 1 --brokers localhost:9092

rpk wasm deploy --name mask-card mask-card/dist/main.js --brokers localhost:9092

rpk topic list --brokers localhost:9092

rpk topic consume coprocessor_internal_topic --offset start -n 1 --brokers localhost:9092

rpk topic produce purchases --brokers localhost:9092

rpk topic list --brokers localhost:9092

rpk topic consume purchases._masked_  --offset start -n 1 --brokers localhost:9092


```

**Comment by mitch-seymour** [comment]
@weimeilin79 it works if you rollback the image (https://github.com/redpanda-data-university/rp-102-stream-processing/pull/5) and also be sure to update the code to what is included in the lesson ([here's another copy](https://github.com/redpanda-data-university/rp-102-stream-processing/blob/main/01-stream-processing-basics/transforms/mask-card-complete/src/main.js) in the repo itself) between these steps:

```sh
rpk topic create purchases

... update the transform code, as indicated in the lesson ...

npm install
npm run build

rpk wasm deploy --name mask-card mask-card/dist/main.js

... etc
```
